version: '3.8'

services:
  portfolio:
    build:
      context: ..
      dockerfile: docker-package/Dockerfile
    container_name: sourav-portfolio
    ports:
      - "8080:8080"
    environment:
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
    volumes:
      # Optional: Mount custom nginx config
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Optional: Mount logs for debugging
      - portfolio-logs:/var/log/nginx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`portfolio.local`)"
      - "traefik.http.services.portfolio.loadbalancer.server.port=8080"
    networks:
      - portfolio-network

  # Optional: Nginx reverse proxy for production
  nginx-proxy:
    image: nginx:1.25-alpine
    container_name: portfolio-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - portfolio
    restart: unless-stopped
    networks:
      - portfolio-network
    profiles:
      - production

volumes:
  portfolio-logs:
    driver: local

networks:
  portfolio-network:
    driver: bridge


